/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package waterappswing.GUI;

import java.awt.Color;

/**
 *
 * @author Marie Noela Abuin
 */
public class Article extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Article.class.getName());

    /**
     * Creates new form Article
     */
    public Article() {
        initComponents();

        displayArticle(0);

        this.getContentPane().setBackground(Color.blue);

    }

    private void displayArticle(int index) {
        String[][] articles = {
            {
                "The Importance of Clean Water",
                "World Health Organization",
                "Clean water is essential for life. It helps prevent diseases such as cholera and typhoid, supports agriculture, and promotes health. Communities with safe water sources experience better growth, education, and productivity."
            },
            {
                "Water Pollution Awareness",
                "UN Environment Programme",
                "Water pollution occurs when harmful substances enter rivers, lakes, and oceans. Reducing plastic use, proper waste disposal, and wastewater treatment are key to protecting aquatic life and human health."
            },
            {
                "Saving Water at Home",
                "Environmental Protection Agency",
                "Simple actions like fixing leaks, turning off taps while brushing, and collecting rainwater can save thousands of liters per household each year."
            }
        };

        if (index >= 0 && index < articles.length) {
            articleCB.setSelectedItem(articles[index][0]);
            authorTF.setText(articles[index][1]);
            contentTA.setText(articles[index][2]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        articleLBL = new javax.swing.JLabel();
        authorLBL = new javax.swing.JLabel();
        contentLBL = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTA = new javax.swing.JTextArea();
        backBTN = new javax.swing.JButton();
        previousBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        articleCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Articles");

        articleLBL.setText("Article title");

        authorLBL.setText("Author");

        contentLBL.setText("Content");

        authorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTFActionPerformed(evt);
            }
        });

        contentTA.setColumns(20);
        contentTA.setRows(5);
        jScrollPane1.setViewportView(contentTA);

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        previousBTN.setText("PREVIOUS");
        previousBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBTNActionPerformed(evt);
            }
        });

        nextBTN.setText("NEXT");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        articleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adavantages of Clean Water", "Water Pollution Awareness", "Saving Water at Home", " " }));
        articleCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleCBActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article.jpeg"))); // NOI18N
        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextBTN)
                        .addGap(34, 34, 34)
                        .addComponent(previousBTN)
                        .addGap(18, 18, 18)
                        .addComponent(backBTN)
                        .addGap(18, 18, 18)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(articleLBL)
                                .addComponent(authorLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contentLBL)
                                .addGap(18, 18, 18)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(articleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 211, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleLBL)
                    .addComponent(articleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLBL)
                    .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 190, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contentLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextBTN)
                            .addComponent(previousBTN)
                            .addComponent(backBTN)
                            .addComponent(exitBTN))
                        .addGap(94, 94, 94))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTFActionPerformed
        // TODO add your handling code here:
        Article author = new Article();
        add(author);
    }//GEN-LAST:event_authorTFActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        String title = (String) articleCB.getSelectedItem();
        String author = authorTF.getText();
        String content = contentTA.getText();

        System.out.println("Article Title: " + title);
        System.out.println("Author: " + author);
        System.out.println("Content: " + content);

        new Education().setVisible(true);
        dispose();

    }//GEN-LAST:event_backBTNActionPerformed

    int currentArticleIndex = 0;

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
        currentArticleIndex = (currentArticleIndex + 1) % 3;
        displayArticle(currentArticleIndex);
    }//GEN-LAST:event_nextBTNActionPerformed

    private void previousBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBTNActionPerformed
        // TODO add your handling code here:
        currentArticleIndex = (currentArticleIndex - 1 + 3) % 3;
        displayArticle(currentArticleIndex);
    }//GEN-LAST:event_previousBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void articleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleCBActionPerformed
        // TODO add your handling code here:
        String selected = (String) articleCB.getSelectedItem();
        System.out.println("Selected article: " + selected);
    }//GEN-LAST:event_articleCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Article().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> articleCB;
    private javax.swing.JLabel articleLBL;
    private javax.swing.JLabel authorLBL;
    private javax.swing.JTextField authorTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel contentLBL;
    private javax.swing.JTextArea contentTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBTN;
    private javax.swing.JButton previousBTN;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
