/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package waterappswing.GUI;

import waterappswing.GUI.MainMenu;
import java.awt.Color;
import javax.swing.JOptionPane;
import waterappswing.MODEL.ReportModel;
import waterappswing.MODEL.ReportType;

/**
 *
 * @author Marie Noela Abuin
 */
public class Report extends javax.swing.JFrame {

    private WaterQuality quality;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Report.class.getName());

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();

        this.getContentPane().setBackground(Color.blue);
    }

    public Report(WaterQuality quality) {
        initComponents();
        this.quality = quality;
        setTitle("Report on " + quality.getSource().getName());
        setLocationRelativeTo(null);
        populateReportTypes();

        reportTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Water Quality", "Pollution", "Shortage", "Sanitation Issue"}
        ));

    }

// Overloaded constructor
    private void populateReportTypes() {
        reportTypeCB.removeAllItems();
        reportTypeCB.addItem("Pollution");
        reportTypeCB.addItem("Water Shortage");
        reportTypeCB.addItem("Sanitation Issue");
        reportTypeCB.addItem("General Feedback");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        reportLBL = new javax.swing.JLabel();
        detailsLBL = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        reportTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTA = new javax.swing.JTextArea();
        reportTypeCB = new javax.swing.JComboBox<>();
        typeLBL = new javax.swing.JLabel();
        exitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Report Management");

        reportLBL.setText("Report title");

        detailsLBL.setText("Details");

        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        reportTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTFActionPerformed(evt);
            }
        });

        detailsTA.setColumns(20);
        detailsTA.setRows(5);
        jScrollPane1.setViewportView(detailsTA);

        reportTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Water Quality", "Pollution", "Shortage", "Sanitation issue" }));
        reportTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTypeCBActionPerformed(evt);
            }
        });

        typeLBL.setText("Report Type");

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportLBL)
                                .addGap(18, 18, 18)
                                .addComponent(reportTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(detailsLBL)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(title))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(typeLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reportTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(saveBTN)
                                .addGap(34, 34, 34)
                                .addComponent(backBTN)
                                .addGap(51, 51, 51)
                                .addComponent(exitBTN)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportLBL)
                            .addComponent(reportTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(detailsLBL)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLBL)
                    .addComponent(reportTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBTN)
                    .addComponent(backBTN)
                    .addComponent(exitBTN))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTFActionPerformed
        // TODO add your handling code here:
        Report reporttitle = new Report();
        add(reporttitle);
    }//GEN-LAST:event_reportTFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        //TODO add your handling code here:
        String reportTitle = reportTF.getText().trim();
        String details = detailsTA.getText().trim();
        String reportType = (String) reportTypeCB.getSelectedItem();

        if (reportTitle.isEmpty() || details.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //ReportType
        ReportType type = new ReportType(reportType);

        //ReportModel
        ReportModel report = new ReportModel(reportTitle, details, type);
        String linkedTo = (quality != null) ? quality.getTitle() : "No specific source";

        // Display
        JOptionPane.showMessageDialog(this, "Report saved successfully!");


    }//GEN-LAST:event_saveBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:                                       
        new MainMenu().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_backBTNActionPerformed

    private void reportTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTypeCBActionPerformed
        // TODO add your handling code here:
        String selected = (String) reportTypeCB.getSelectedItem();
        System.out.println("Selected report type: " + selected);

    }//GEN-LAST:event_reportTypeCBActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Report().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel detailsLBL;
    private javax.swing.JTextArea detailsTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reportLBL;
    private javax.swing.JTextField reportTF;
    private javax.swing.JComboBox<String> reportTypeCB;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel title;
    private javax.swing.JLabel typeLBL;
    // End of variables declaration//GEN-END:variables
}
