/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package waterappswing.GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import waterappswing.MODEL.WaterQualityModel;
import waterappswing.MODEL.WaterSourceModel;

/**
 *
 * @author Marie Noela Abuin
 *
 */
public class WaterQuality extends javax.swing.JFrame {

    private WaterSourceModel source;

    public WaterQuality(WaterSourceModel source) {
        initComponents();
        this.source = source;

        displayWaterQuality();

        this.getContentPane().setBackground(Color.blue);
    }

    public WaterQuality() {
        this(new WaterSourceModel("Unknown Source", "Unknown Location"));
    }

    public WaterSourceModel getSource() {
        return source;
    }

    private void displayWaterQuality() {
        String location = source.getLocation().toLowerCase();

        String pHLevel;
        String contaminant;
        String quality;

        if (location.contains("river")) {
            pHLevel = "7.2";
            contaminant = "Nitrates";
            quality = "Good";
        } else if (location.contains("lake")) {
            pHLevel = "3.4";
            contaminant = "Industrial waste";
            quality = "Bad";
        } else {
            pHLevel = "7.0";
            contaminant = "Unknown";
            quality = "Pending Analysis";
        }

        pHTF.setText(pHLevel);
        contaminantTF.setText(contaminant);
        qualityTF.setText(quality);

        pHTF.setEditable(false);
        contaminantTF.setEditable(false);
        qualityTF.setEditable(false);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pHLBL = new javax.swing.JLabel();
        contaminantLBL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qualityLBL = new javax.swing.JLabel();
        pHTF = new javax.swing.JTextField();
        contaminantTF = new javax.swing.JTextField();
        qualityTF = new javax.swing.JTextField();
        backBTN = new javax.swing.JButton();
        createReportBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Water Quality");

        pHLBL.setText("pH level");

        contaminantLBL.setText("Contaminant");

        qualityLBL.setText("Quality ");

        pHTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pHTFActionPerformed(evt);
            }
        });

        contaminantTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaminantTFActionPerformed(evt);
            }
        });

        qualityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualityTFActionPerformed(evt);
            }
        });

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        createReportBTN.setText("CREATE REPORT");
        createReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contaminantLBL)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pHTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contaminantTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pHLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qualityLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qualityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(createReportBTN)
                        .addGap(18, 18, 18)
                        .addComponent(backBTN)
                        .addGap(37, 37, 37)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(title)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pHLBL)
                            .addComponent(pHTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contaminantLBL)
                            .addComponent(contaminantTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qualityLBL)
                            .addComponent(qualityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createReportBTN)
                    .addComponent(backBTN)
                    .addComponent(exitBTN))
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qualityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualityTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_qualityTFActionPerformed

    private void pHTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pHTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pHTFActionPerformed

    private void contaminantTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaminantTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_contaminantTFActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        new WaterSource().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void createReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReportBTNActionPerformed
        // TODO add your handling code here:                                                                                                                                    
    try {
        String contaminant = contaminantTF.getText().trim();
        String qualityGrade = qualityTF.getText().trim();
        double pHLevel = Double.parseDouble(pHTF.getText().trim());

        WaterQualityModel model = new WaterQualityModel(contaminant, qualityGrade, pHLevel);

        javax.swing.JOptionPane.showMessageDialog(this,
            "Water Quality Report Created!\n\n" + model.toString(),
            "Report Saved",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter a valid numeric value for pH Level.",
            "Invalid Input",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }




    }//GEN-LAST:event_createReportBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WaterQuality().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel contaminantLBL;
    private javax.swing.JTextField contaminantTF;
    private javax.swing.JButton createReportBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel pHLBL;
    private javax.swing.JTextField pHTF;
    private javax.swing.JLabel qualityLBL;
    private javax.swing.JTextField qualityTF;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
